### ISSUE TITLE
Просьба

### ISSUE THREAD

**Issue by TweeLeeS** [EvelynFreemanDS/lambdabot#1]
Меня попросили написать, я не знаю зачем или как это поможет проекту, но в я нашёл ошибку в коде.  
![image](https://user-images.githubusercontent.com/52028536/59829499-09f50080-9357-11e9-9c0f-c2266ad897cf.png)

Такого слова нет в русском языке kek

**Comment by EvelynFreemanDS** [comment]
Пофиг на слово

Так что за ошибка?
